services:
  - type: web
    name: pinyimage-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pinyimage-db
          property: connectionString

databases:
  - name: pinyimage-db
    databaseName: pinyimage
    user: pinyimage_user
    plan: free
